// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRSrTVZ9NoK64nsuK1KTMskz7w5bwWLIA',
    appId: '1:707831176489:web:73ca75c2a9a7d8df97ab38',
    messagingSenderId: '707831176489',
    projectId: 'authlogin-19259',
    authDomain: 'authlogin-19259.firebaseapp.com',
    storageBucket: 'authlogin-19259.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRYWuMuRnRanKOaPlPieoI9xvmZ5nq6lw',
    appId: '1:707831176489:android:9edade74c3f118d297ab38',
    messagingSenderId: '707831176489',
    projectId: 'authlogin-19259',
    storageBucket: 'authlogin-19259.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzSVgJnLRCxPnHiUcZTGzGqZiJAn4SuOg',
    appId: '1:707831176489:ios:fb35697f5aed7a6297ab38',
    messagingSenderId: '707831176489',
    projectId: 'authlogin-19259',
    storageBucket: 'authlogin-19259.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzSVgJnLRCxPnHiUcZTGzGqZiJAn4SuOg',
    appId: '1:707831176489:ios:fb35697f5aed7a6297ab38',
    messagingSenderId: '707831176489',
    projectId: 'authlogin-19259',
    storageBucket: 'authlogin-19259.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
